# Hierarchical Partial-Order (HPO) Model Simulation

This document provides a comprehensive guide to simulating data from a **Hierarchical Partial-Order (HPO) Model**. The HPO model is designed to generate hierarchical structures of partial orders based on latent variables influenced by multiple assessors. This simulation accounts for global latent scores, assessor-specific deviations, and observed ranking data within specified choice sets.

## Model Overview

The Hierarchical Partial-Order (HPO) model operates under the following hierarchical structure:

1. **Global Latent Scores**:
   \[
   U^{(0)} \sim \mathcal{N}(\mathbf{0}, \Sigma_\rho)
   \]
   Each item \( j \in M_0 \) has a global latent score \( U_j^{(0)} \) drawn from a multivariate normal distribution with mean vector \( \mathbf{0} \) and covariance matrix \( \Sigma_\rho \).

2. **Assessor-Specific Latent Scores**:
   \[
   U^{(a)}_j \mid U^{(0)}_j \sim \mathcal{N}(\tau \cdot U^{(0)}_j, (1 - \tau^2) \cdot \Sigma_\rho)
   \]
   For each assessor \( a \in A \) and each item \( j \in M_a \subseteq M_0 \), the assessor-specific latent score \( U^{(a)}_j \) is drawn from a multivariate normal distribution centered at \( \tau \cdot U^{(0)}_j \) with covariance \( (1 - \tau^2) \cdot \Sigma_\rho \).

3. **Transformation to Preference Scores**:
   \[
   \eta_j^{(a)} = G^{-1}(\Phi(U_j^{(a)})) + \alpha_j
   \]
   The latent scores \( U_j^{(a)} \) are transformed into preference scores \( \eta_j^{(a)} \) using the inverse Gumbel CDF \( G^{-1} \) applied to the standard normal CDF \( \Phi(U_j^{(a)}) \), followed by the addition of item-specific effects \( \alpha_j \).

4. **Generation of Partial Orders**:
   \[
   h^{(a)} = h(\eta^{(a)})
   \]
   Each preference score matrix \( \eta^{(a)} \) is converted into a partial order \( h^{(a)} \) by establishing directed edges between items based on their preference scores across all dimensions.

5. **Restriction to Choice Sets**:
   Each partial order \( h^{(a)} \) is further restricted to smaller choice sets \( O_{a,i} \) to reflect observed rankings.

## Function: `simulate_HPO_with_tasks`

The `simulate_HPO_with_tasks` function encapsulates the simulation process of the HPO model. It generates global and assessor-specific latent scores, transforms them into preference scores, constructs partial orders, and restricts these orders to specified choice sets.

### Function Definition

In [29]:
import numpy as np
import math
from scipy.stats import multivariate_normal, norm
import networkx as nx
import random
import seaborn as sns
import pandas as pd
from collections import Counter, defaultdict
import itertools
import matplotlib.pyplot as plt
from typing import List, Optional, Dict, Any
import sys as sys

# Make sure these paths and imports match your local project structure
sys.path.append('../src/utils')  # Example path
from po_fun import BasicUtils, StatisticalUtils#
from mallow_function import Mallows
#from po_accelerator import LogLikelihoodCache
from typing import Dict, List

# Transform Eta change the G function 
# The initial setting is not correct, we need to have the O_i variable , and then we could generate the hierachical relationship out

# Then deploy the partial order relationship 

# Peform the MCMC simulation alogrithem and think the method about how to write it 

In [30]:

def G_inv(p):
    # Gumbel quantile function
    # Safeguard tiny p to avoid log(0)
    eps = 1e-15
    p_safe = np.clip(p, eps, 1 - eps)
    return -np.log(-np.log(p_safe))



In [31]:
M0 = [0, 1, 2, 3, 4, 5] ## This is the total list 
assessors = [1, 2, 3]
# (Sometimes called the "leaf" sets M_a in the partial-order hierarchy.)
M_a_list = [
    [0, 2, 4],   # M_1
    [1, 2, 3],   # M_2
    [1, 3, 4]    # M_3
]

# For each assessor a, the list of choice sets O_{a,i}
# Meaning: in each "task" or "batch", assessor a was asked to rank this subset.
# We'll store them in a dictionary keyed by assessor, 
# each value is a list of subsets (choice sets).
O_a_i_dict = {
    1: [
        [0, 2, 4],
        [0, 2]
    ],
    2: [
        [1, 2,5],
        [1, 3],
        [1,4,5]
    ],
    3: [
        [1, 3],
        [1, 3, 4],
        [2,4,5]
    ]
}

# Observed orders y_{a,i} (one for each choice set above).
# For instance, y_{1,0} is an order of [0,4,2] (lowest rank first or highest first, depending on convention).
# We'll store these in the same dictionary shape.
# These are "real" or "observed" orders for the subsets O_{a,i}.
y_a_i_dict = {
    1: [
        [0, 4, 2],   # observed order for subset [0,2,4]
        [0, 2]       # observed order for subset [0,2]
    ],
    2: [
        [1, 2],      # observed order for subset [1,2],will yi contain a full rank for partial order 
        [3, 1]       # observed order for subset [1,3]
        # [1, 4]       # observed order for subset [1,4,5]
    ],
    3: [
        [3, 1],      # observed order for subset [1,3]
        [4, 3, 1],   # observed order for subset [1,3,4]
        [5,4,2]
    ]
}

alpha = np.array([0.5, -0.2, 0.3, 0.1, 0.0, 1.2]) # The characteristic vector for the object, which is a score , alpha is beta*X , alpha is the global variable and need M0 dimension 

In [32]:
K = 2 
rho = 0.9 # Should follow a beta distributino, let's assume this first 
tau = 0.8# should follow a beta distributino, let's assume this first 

Simulate from the hierarchical partial-order model, requiring:
      U^(0) ~ N(0, Sigma_rho),
      U^(a) | U^(0) ~ N(tau * U^(0), (1 - tau^2)*Sigma_rho),
      eta^(a) = G^-1( Phi(U^(a)) ) + alpha_j,
      h^(a)   = partial order from eta^(a).

    Then restrict each h^(a) to the smaller choice sets O_{a,i}.

    Parameters
    ----------
    M0 : List[int]
        Global set of items (indices).
    assessors : List[int]
        List of assessor IDs (1, 2, 3, ...).
    M_a_list : List[List[int]]
        For each assessor a, which items they rank. Must align with assessors.
    O_a_i_dict : Dict[int, List[List[int]]]
        For each assessor a, a list of choice sets (subsets).
    alpha : np.ndarray
    K : int
        Dimensionality of latent space.
    rho : float
        Off-diagonal correlation in compound-symmetric covariance Sigma_rho.
    tau : float
        Correlation-like parameter in [0, 1].
    random_seed : int
        Global random seed for reproducibility.

    Returns
    -------
    results : Dict[str, Any]
        Contains:
          - 'U0': (|M0| x K) global latent scores,
          - 'U_a': list of (|M_a| x K) latents for each assessor a,
          - 'eta_a': list of (|M_a| x K) after Gumbel transform + alpha,
          - 'h_a': list of adjacency matrices (|M_a| x |M_a|),
          - 'h_a_i': dict-of-dicts for partial orders restricted to O_{a,i}.

In [33]:
def simulate_HPO_with_tasks(
    M0: List[int],
    assessors: List[int],
    M_a_list: List[List[int]],
    O_a_i_dict: Dict[int, List[List[int]]],
    alpha: np.ndarray,            # Must be non-None and length = len(M0)
    K: int,
    rho: float,
    tau: float,
    random_seed: int = 42
):
 
    # ----------------------------
    # 1) Setup: random seed & covariance
    # ----------------------------
    rng = np.random.default_rng(random_seed)  # single global RNG
    random.seed(random_seed)                  # for any other random usage

    # Build the correlation matrix Sigma_rho (compound-symmetric)
    Sigma_rho = np.full((K, K), rho, dtype=float)
    np.fill_diagonal(Sigma_rho, 1.0)

    # Validate alpha length
    n_global = len(M0)
    if len(alpha) != n_global:
        raise ValueError(
            f"alpha must have length {n_global}, but got length {len(alpha)}"
        )

    # ----------------------------
    # 2) Global Latent U^(0)
    # ----------------------------
    mvn_global = multivariate_normal(mean=np.zeros(K), cov=Sigma_rho)
    U0 = mvn_global.rvs(size=n_global)  # shape: (n_global, K)

    # ----------------------------
    # 3) Assessor-level Latents
    # ----------------------------
    U_a_list = []
    eta_a_list = []
    h_a_list = []
    h_a_i = {a: {} for a in assessors}  # partial orders restricted to tasks

    for idx, a in enumerate(assessors):
        # Items for this assessor:
        Ma = M_a_list[idx]
        n_a = len(Ma)

        # For j in M_a: U^(a)_j ~ N( tau*U^(0)_j, (1 - tau^2)*Sigma_rho )
        # We do it based on each object j in this question.
        Ua = np.zeros((n_a, K), dtype=float)
        for i_loc, j_global in enumerate(Ma):
            mean_vec = tau * U0[j_global, :]
            cov_mat  = (1 - tau**2) * Sigma_rho
            Ua[i_loc, :] = rng.multivariate_normal(mean=mean_vec, cov=cov_mat)
        U_a_list.append(Ua)

        # Transform to Gumbel-based eta^(a)
        eta_a = np.zeros_like(Ua)
        for i_loc, j_global in enumerate(Ma):
            # step 1: Gaussian -> Uniform(0,1)
            p_vec = norm.cdf(Ua[i_loc, :])
            # step 2: Uniform(0,1) -> Gumbel -> + alpha
            gumbel_vec = np.array([G_inv(p) for p in p_vec])
            eta_a[i_loc, :] = gumbel_vec + alpha[j_global]
        eta_a_list.append(eta_a)

        # partial order h^(a)
        h_a = BasicUtils.generate_partial_order(eta_a)
        h_a_list.append(h_a)

        # Restrict partial order to each choice set O_{a,i}
        O_list = O_a_i_dict.get(a, [])
        for i_task, subset in enumerate(O_list):
            subset_indices_in_Ma = []
            for item_j in subset:
                if item_j in Ma:
                    local_idx = Ma.index(item_j)
                    subset_indices_in_Ma.append(local_idx)

            sub_size = len(subset_indices_in_Ma)
            h_sub = np.zeros((sub_size, sub_size), dtype=int)
            for r, i_loc_ in enumerate(subset_indices_in_Ma):
                for c, j_loc_ in enumerate(subset_indices_in_Ma):
                    h_sub[r, c] = h_a[i_loc_, j_loc_]
            
            h_a_i[a][i_task] = h_sub

    # ----------------------------
    # Return results
    # ----------------------------
    results = {
        'U0': U0,         # shape (|M0|, K)
        'U_a': U_a_list,  # list of length = # of assessors
        'eta_a': eta_a_list,
        'h_a': h_a_list,
        'h_a_i': h_a_i
    }
    return results

In [34]:
results = simulate_HPO_with_tasks(
    M0=M0,
    assessors=assessors,
    M_a_list=M_a_list,
    O_a_i_dict=O_a_i_dict,
    alpha=alpha,         # Not None
    K=2,
    rho=0.3,
    tau=0.8,
    random_seed=2025     # Global random seed
)

In [35]:
print("\n--- Global U^(0) ---")
print(results['U0'])

for idx, a in enumerate(assessors):
    print(f"\nAssessor {a}")
    print("  U^(a):\n", results['U_a'][idx])
    print("  eta^(a):\n", results['eta_a'][idx])
    print("  h^(a) adjacency:\n", results['h_a'][idx])

    # Show restricted partial orders
    for i_task, O_subset in enumerate(O_a_i_dict[a]):
        print(f"  Task {i_task}, O_{a,i_task} = {O_subset}")
        print("    restricted adjacency:\n", results['h_a_i'][a][i_task])


--- Global U^(0) ---
[[ 0.48895212 -0.62589801]
 [ 0.39564124 -1.31760809]
 [ 1.15817296  1.67569046]
 [ 0.41622277  0.23918466]
 [ 0.08670167 -0.88035684]
 [-0.08601646 -0.18616445]]

Assessor 1
  U^(a):
 [[1.45643201 0.58300983]
 [1.58808047 1.20044712]
 [0.97889183 0.74861902]]
  eta^(a):
 [[3.08481816 1.61344563]
 [3.15126579 2.40251959]
 [1.72088666 1.35660968]]
  h^(a) adjacency:
 [[0 0 1]
 [1 0 1]
 [0 0 0]]
  Task 0, O_(1, 0) = [0, 2, 4]
    restricted adjacency:
 [[0 0 1]
 [1 0 1]
 [0 0 0]]
  Task 1, O_(1, 1) = [0, 2]
    restricted adjacency:
 [[0 0]
 [1 0]]

Assessor 2
  U^(a):
 [[ 0.58923709 -0.59181387]
 [ 0.4833693   1.10476886]
 [ 0.19496226  0.52101298]]
  eta^(a):
 [[ 0.92231923 -0.44981078]
 [ 1.27422345  2.23379796]
 [ 0.69890539  1.12621594]]
  h^(a) adjacency:
 [[0 0 0]
 [1 0 1]
 [0 0 0]]
  Task 0, O_(2, 0) = [1, 2, 5]
    restricted adjacency:
 [[0 0]
 [1 0]]
  Task 1, O_(2, 1) = [1, 3]
    restricted adjacency:
 [[0 0]
 [0 0]]
  Task 2, O_(2, 2) = [1, 4, 5]
    r